/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Aac: () => import('#controllers/aac_controller'),
  Accueil: () => import('#controllers/accueil_controller'),
  Exploitations: () => import('#controllers/exploitations_controller'),
  LogEntries: () => import('#controllers/log_entries_controller'),
  ProjectSteps: () => import('#controllers/project_steps_controller'),
  Projects: () => import('#controllers/projects_controller'),
  Session: () => import('#controllers/session_controller'),
  Territoires: () => import('#controllers/territoires_controller'),
  Visualisation: () => import('#controllers/visualisation_controller'),
}
