/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class CaptageSchema extends BaseModel {
  static $columns = ['bssCode', 'code', 'commune', 'createdAt', 'id', 'name', 'prioritaire', 'state', 'type', 'updatedAt'] as const
  $columns = CaptageSchema.$columns
  @column()
  declare bssCode: string
  @column()
  declare code: string
  @column()
  declare commune: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare prioritaire: boolean
  @column()
  declare state: string
  @column()
  declare type: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ContactSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'exploitationId', 'firstName', 'id', 'isPrimaryContact', 'lastName', 'phoneNumber', 'role', 'updatedAt'] as const
  $columns = ContactSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare email: string | null
  @column()
  declare exploitationId: string
  @column()
  declare firstName: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isPrimaryContact: boolean
  @column()
  declare lastName: string | null
  @column()
  declare phoneNumber: string | null
  @column()
  declare role: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CultureGroupSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'label', 'updatedAt'] as const
  $columns = CultureGroupSchema.$columns
  @column({ isPrimary: true })
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare label: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CultureSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'endingYear', 'groupCode', 'label', 'startingYear', 'updatedAt'] as const
  $columns = CultureSchema.$columns
  @column({ isPrimary: true })
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare endingYear: number | null
  @column()
  declare groupCode: string | null
  @column()
  declare label: string
  @column()
  declare startingYear: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class EventLogSchema extends BaseModel {
  static $columns = ['context', 'createdAt', 'id', 'name', 'step', 'userId', 'version'] as const
  $columns = EventLogSchema.$columns
  @column()
  declare context: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string | null
  @column()
  declare step: string | null
  @column()
  declare userId: string | null
  @column()
  declare version: number | null
}

export class ExploitationTagSchema extends BaseModel {
  static $columns = ['createdAt', 'group', 'id', 'name', 'updatedAt'] as const
  $columns = ExploitationTagSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare group: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ExploitationTagsRelationSchema extends BaseModel {
  static $columns = ['createdAt', 'exploitationId', 'exploitationTagId', 'id', 'updatedAt'] as const
  $columns = ExploitationTagsRelationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare exploitationId: string
  @column()
  declare exploitationTagId: number
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ExploitationTerritoireRelationSchema extends BaseModel {
  static $columns = ['createdAt', 'exploitationId', 'id', 'territoireId', 'updatedAt'] as const
  $columns = ExploitationTerritoireRelationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare exploitationId: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare territoireId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ExploitationSchema extends BaseModel {
  static $columns = ['activite', 'addressLine1', 'addressLine2', 'commune', 'createdAt', 'denominationLegale', 'formeJuridique', 'id', 'isDeleted', 'location', 'name', 'notes', 'postalBox', 'postalCode', 'siret', 'updatedAt', 'userId'] as const
  $columns = ExploitationSchema.$columns
  @column()
  declare activite: string | null
  @column()
  declare addressLine1: string | null
  @column()
  declare addressLine2: string | null
  @column()
  declare commune: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare denominationLegale: string | null
  @column()
  declare formeJuridique: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isDeleted: boolean
  @column()
  declare location: string | null
  @column()
  declare name: string
  @column()
  declare notes: string | null
  @column()
  declare postalBox: string | null
  @column()
  declare postalCode: string | null
  @column()
  declare siret: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string | null
}

export class LogEntrySchema extends BaseModel {
  static $columns = ['createdAt', 'date', 'exploitationId', 'id', 'isCompleted', 'notes', 'title', 'updatedAt', 'userId'] as const
  $columns = LogEntrySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.date()
  declare date: DateTime | null
  @column()
  declare exploitationId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isCompleted: boolean
  @column()
  declare notes: string | null
  @column()
  declare title: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class LogEntryDocumentSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'logEntryId', 'name', 's3Key', 'sizeInBytes', 'updatedAt'] as const
  $columns = LogEntryDocumentSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare logEntryId: string
  @column()
  declare name: string
  @column()
  declare s3Key: string
  @column()
  declare sizeInBytes: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LogEntryTagRelationSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'logEntryId', 'logEntryTagId', 'updatedAt'] as const
  $columns = LogEntryTagRelationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare logEntryId: string
  @column()
  declare logEntryTagId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LogEntryTagSchema extends BaseModel {
  static $columns = ['createdAt', 'exploitationId', 'id', 'name', 'updatedAt', 'userId'] as const
  $columns = LogEntryTagSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare exploitationId: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class ParcelleCommentSchema extends BaseModel {
  static $columns = ['comment', 'createdAt', 'id', 'parcelleId', 'updatedAt', 'userId'] as const
  $columns = ParcelleCommentSchema.$columns
  @column()
  declare comment: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare parcelleId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class ParcelleSchema extends BaseModel {
  static $columns = ['centroid', 'createdAt', 'cultureCode', 'exploitationId', 'id', 'rpgId', 'surface', 'updatedAt', 'year'] as const
  $columns = ParcelleSchema.$columns
  @column()
  declare centroid: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare cultureCode: string | null
  @column()
  declare exploitationId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare rpgId: string | null
  @column()
  declare surface: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare year: number
}

export class ProjectCaptageRelationSchema extends BaseModel {
  static $columns = ['captageId', 'createdAt', 'id', 'projectId', 'updatedAt'] as const
  $columns = ProjectCaptageRelationSchema.$columns
  @column()
  declare captageId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare projectId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProjectExploitationRelationSchema extends BaseModel {
  static $columns = ['createdAt', 'exploitationId', 'id', 'projectId', 'updatedAt'] as const
  $columns = ProjectExploitationRelationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare exploitationId: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare projectId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProjectParcelleRelationSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'parcelleId', 'projectId', 'updatedAt'] as const
  $columns = ProjectParcelleRelationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare parcelleId: string
  @column()
  declare projectId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProjectStepDocumentSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'projectStepId', 's3Key', 'sizeInBytes', 'updatedAt'] as const
  $columns = ProjectStepDocumentSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare projectStepId: string
  @column()
  declare s3Key: string
  @column()
  declare sizeInBytes: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProjectStepTagRelationSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'projectStepId', 'projectStepTagId', 'updatedAt'] as const
  $columns = ProjectStepTagRelationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare projectStepId: string
  @column()
  declare projectStepTagId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProjectStepTagSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'updatedAt', 'userId'] as const
  $columns = ProjectStepTagSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class ProjectStepSchema extends BaseModel {
  static $columns = ['createdAt', 'date', 'id', 'isValidated', 'note', 'projectId', 'title', 'updatedAt'] as const
  $columns = ProjectStepSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.date()
  declare date: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isValidated: boolean
  @column()
  declare note: string | null
  @column()
  declare projectId: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProjectSchema extends BaseModel {
  static $columns = ['actionType', 'closedAt', 'createdAt', 'description', 'id', 'name', 'status', 'updatedAt', 'userId'] as const
  $columns = ProjectSchema.$columns
  @column()
  declare actionType: string | null
  @column.dateTime()
  declare closedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class RememberMeTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'hash', 'id', 'tokenableId', 'updatedAt'] as const
  $columns = RememberMeTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenableId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class TerritoireUserRelationSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'territoireId', 'updatedAt', 'userId'] as const
  $columns = TerritoireUserRelationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare territoireId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class TerritoireSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'id', 'name', 'parentTerritoireId', 'updatedAt'] as const
  $columns = TerritoireSchema.$columns
  @column()
  declare code: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string | null
  @column()
  declare parentTerritoireId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: string
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
