/*
|--------------------------------------------------------------------------
| Bouncer policies
|--------------------------------------------------------------------------
|
| This file is auto-generated by the `ace make:policy` command.
| You can edit the policies and their permissions in the respective files in the `app/policies` directory.
|
*/

export const policies = {
  ExploitationPolicy: () => import('#policies/exploitation_policy'),
}
